Created API documentation using swagger
kiran-anand14/admgr pull request #1
Opened 2023-04-28 03:10 UTC by parvez0

For testing swagger api https://editor.swagger.io/ you can go to this URL and upload the swagger yaml file

2023-04-28 22:30 UTC, kiran-anand14 requested changes

2023-04-28 22:30 UTC, kiran-anand14 commented on swagger.yml
> +                  $ref: '#/components/schemas/Slot'
Suppose a user wanted access slot information for date range 29-Apr till 02-May. A successful response should look like this:

```
[
  {
    "date": "2023-04-29",
    "status": "open",
    "slots": [
      {
        "position": 1,
        "cost": 0,
        "status": "open"
      },
      {
        "position": 2,
        "cost": 0,
        "status": "booked"
      },
      {
        "position": 3,
        "cost": 0,
        "status": "booked"
      },
      {
        "position": 4,
        "cost": 0,
        "status": "booked"
      },
      {
        "position": 5,
        "cost": 0,
        "status": "open"
      }
    ]
  },
  {
    "date": "2023-04-30",
    "status": "open",
    "slots": [
      {
        "position": 1,
        "cost": 0,
        "status": "booked"
      },
      {
        "position": 2,
        "cost": 0,
        "status": "booked"
      },
      {
        "position": 3,
        "cost": 0,
        "status": "booked"
      },
      {
        "position": 4,
        "cost": 0,
        "status": "hold"
      },
      {
        "position": 5,
        "cost": 0,
        "status": "open"
      }
    ]
  },
  {
    "date": "2023-05-01",
    "status": "closed"
  },
  {
    "date": "2023-05-02",
    "status": "closed"
  }
]
```

2023-04-28 22:30 UTC, kiran-anand14 commented on swagger.yml
> +          description: Validation exception
See and modify these responses wherever required in light of my comments for POST /adslots API endpoint.

2023-04-28 22:30 UTC, kiran-anand14 commented on swagger.yml
> +            format: uuid
Which Id is this? POST method hadn't returned any Id. It is not needed.

2023-04-28 22:30 UTC, kiran-anand14 commented on swagger.yml
> +        required: true
Payload will be same as used in POST /adslots request. Do you agree?

2023-04-28 22:30 UTC, kiran-anand14 commented on swagger.yml
> +          description: Validation exception
Responses will also be similar to POST /adslots API. Do you agree?

2023-04-28 22:30 UTC, kiran-anand14 commented on swagger.yml
> +    post:
let us change it to PATCH only.

2023-04-28 22:30 UTC, kiran-anand14 commented on swagger.yml
> +            format: uuid
Again Id is not needed.

2023-04-28 22:30 UTC, kiran-anand14 commented on swagger.yml
> +        required: true
Request body for a user booking slots for booking different dates should be as follows. I have tried to keep it simple. Do you agree?

```
[
  {
    "date": "2023-04-29",
    "position": 1
  },
  {
    "date": "2023-05-01",
    "position": 2
  },
  {
    "date": "2023-04-29",
    "position": 1
  },
  {
    "date": "2023-05-02",
    "position": 2
  },
  {
    "date": "2023-05-07",
    "position": 5
  }
]
```

2023-04-28 22:30 UTC, kiran-anand14 commented on swagger.yml
> +          description: Invalid status value
Consider response codes in light of response code related comments provided for POST /adslots API.

403 Forbidden can be especially used:
- if user tries to reserve a slot that is already 'booked' or on 'hold'
- Tries to book a slot from date which is not 'open'
- Tries to book a slot in the date which has already passed.

2023-04-28 22:32 UTC, kiran-anand14 commented on swagger.yml
> +openapi: 3.0.3
Make an "api" directory and add this files in it.

2023-04-28 23:44 UTC, parvez0 commented on swagger.yml
> +openapi: 3.0.3
I didn't have the permission to push on the other branch so I had to create a fork out of it, can you verify my credentials for creating and raising a PR against main

2023-04-29 00:15 UTC, parvez0 commented on swagger.yml
> +                $ref: '#/components/schemas/ApiResponse'
Changing it will only return ok

2023-04-29 00:25 UTC, kiran-anand14 commented on swagger.yml
> +openapi: 3.0.3
Try creating and pushing "parvez-dev-br", let me know if it doesn't work.

2023-04-29 00:35 UTC, parvez0 commented on swagger.yml
> +              $ref: '#/components/schemas/Adslots'
Yeah it's simplified a lot of things also changed start_dt to start_date

2023-04-29 00:35 UTC, parvez0 commented on swagger.yml
> +          description: Not found
removed it

2023-04-29 00:36 UTC, parvez0 commented on swagger.yml
> +          description: Validation exception
Removed 405 as well

2023-04-29 01:08 UTC, parvez0 commented on swagger.yml
> +            format: uuid
This Id was mentioned the requirement documents should we remove it?

2023-04-30 17:43 UTC, kiran-anand14 requested changes

2023-04-30 17:43 UTC, kiran-anand14 commented on documentation/swagger.yml
> +info:
Define another swagger test files as well for REST API interface with 'accounting' service. You will have to use it for your testing.

2023-05-01 14:05 UTC, kiran-anand14 commented on documentation/swagger.yml
> +            format: uuid
Discussed and Resolved.

2023-05-01 14:15 UTC, kiran-anand14 commented on documentation/swagger.yml
> +            properties:
Change [open, closed, hold] to [open, closed, hold, booked]

2023-05-03 16:52 UTC, kiran-anand14 requested changes

2023-05-03 16:52 UTC, kiran-anand14 commented on api/swagger.yml
> +    get:
I think we need to break GET API into two APIs, though internal implementation will have most of the logic common.

Think of it like this:
- Admin would like to see all the slots for n number of days. So for admin GET /adslots, Query Params: date range is fine. Response would include which ones are open, which ones are booked, who has booked them and at what time. Current response you have defined is catering to this requirement.
- A User when he opens calendar for booking, it should be able to see all the slots for date range, which one are open and which one are booked. API he would be: GET /adslots, Query Params: user_id, status=open and date range. After choosing the slots he wants to book, he will issue PATCH /adslots API. We will be able to handle this use case also with current response that you have defined.
- Now think of a scenario where user is interested in looking at history of what slots he has booked in a date range. I think for that we would need another API: GET /adslots/findByUserId, Query Params: user_id. It will return all the slots booked by this user in a certain date range. I think implementation wise, most of the code will be the same, only entry point http handler will change and you will have to query DB in different variations.

2023-05-03 16:52 UTC, kiran-anand14 commented on api/swagger.yml
> +    get:
Or do one thing: No need to implement GET /adslots/findByUserId API.

Instead in the 2nd API, replace booked_by field in response with "me" if user_id in URL query parameter matches with the person who has booked the slot, otherwise "other". End user should not be able to see the ids of other users.

Let me know if you have any doubt.

2023-05-03 16:52 UTC, kiran-anand14 commented on scripts/db/seeder.sql
> +  `cost` DECIMAL(10,2) NULL COMMENT 'Cost of the slots decimal value update 3 numbers',
Cost is also a non-null value.

2023-05-03 16:52 UTC, kiran-anand14 commented on scripts/db/seeder.sql
> +  PRIMARY KEY (`id`),
Primary key in this table is also a combination of date and position as it is in slots table.

2023-05-03 16:52 UTC, kiran-anand14 commented on scripts/db/seeder.sql
> +  `id` VARCHAR(36) NOT NULL COMMENT 'Unique Id identifying the slots',
Change id to txnid and it is not a primary key, but it should be unique and not null. Add unique constraint on it.

2023-05-03 16:52 UTC, kiran-anand14 commented on api/accounting.yml
> +        cost:
It should be amount and it should be the sum of all costs of the slots array.

2023-05-03 16:52 UTC, kiran-anand14 commented on api/accounting.yml
> +      requestBody:
Request body should also mention the Source ("source": "admgr") of the request i.e. which service has initiated this debit request.

2023-05-03 16:52 UTC, kiran-anand14 commented on api/accounting.yml
> +  /transaction:
Change endpoint name to /debit

2023-05-03 16:52 UTC, kiran-anand14 commented on api/accounting.yml
> +          cost: 0
slots should be inside metadata {}

```
"metadata": {
  "slots": [
    {
      "date": "05-05-2023",
      "position": 1,
      "cost": 1.23
    },
    {
      "date": "05-05-2023",
      "position": 2,
      "cost": 12.3
    },
    {
      "date": "05-05-2023",
      "position": 3,
      "cost": 0
    }
  ]
}
```

2023-05-04 21:30 UTC, kiran-anand14 approved these changes

2023-05-04 21:32 UTC, merged